package io.github.opengutool.views.form;

import io.github.opengutool.views.func.JavaConsoleForm;
import io.github.opengutool.views.util.MacWindowUtil;
import lombok.Getter;

import javax.swing.*;

/**
 * <pre>
 * 主界面
 * </pre>
 *
 * @author <a href="https://github.com/opengutool">gutool</a>
 * @since 2025/9/3
 */
@Getter
public class MainWindow {
    private JPanel mainPanel;

    private static MainWindow mainWindow;

    private MainWindow() {
    }

    public static MainWindow getInstance() {
        if (mainWindow == null) {
            mainWindow = new MainWindow();
        }
        return mainWindow;
    }

    public void init() {
        mainWindow = getInstance();
        mainWindow.getMainPanel().updateUI();
        MacWindowUtil.configureMacInsets(mainPanel, MacWindowUtil.MAIN_PANEL_INSETS);
        mainWindow.getMainPanel().updateUI();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        mainPanel = JavaConsoleForm.getInstance().getJavaConsolePanel();
    }
}
